services:
  postgres:
    image: postgres:16-alpine
    container_name: amanecer-rural-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: amanecer_rural
      POSTGRES_USER: ar_user
      POSTGRES_PASSWORD: ar_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ar-network

  redis:
    image: redis:7-alpine
    container_name: amanecer-rural-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - ar-network

volumes:
  pgdata:
  redisdata:

networks:
  ar-network:
    driver: bridge
