services:
  postgres:
    image: postgres:16-alpine
    container_name: amanecer-rural-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: amanecer_rural
      POSTGRES_USER: ar_user
      POSTGRES_PASSWORD: ar_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ar-network

  redis:
    image: redis:7-alpine
    container_name: amanecer-rural-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - ar-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: amanecer-rural-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@amanecerrural.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - ar-network

volumes:
  pgdata:
  redisdata:

networks:
  ar-network:
    driver: bridge
